name: Submission PR Review
on: pull_request
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - run: cat ${{github.event.pull_request}}
      - uses: actions/checkout@v2
      - run: cat README.md